version: '3.9'

networks:
  php-crud-network:

services:
  database:
    image: mysql:8
    container_name: php-crud-db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "php_crud"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./database:/var/lib/mysql

    networks:
      - php-crud-network